#!/bin/bash

DESKTOPS=$(xdotool get_num_desktops)
FOCUSDESKTOP=$(xdotool get_desktop)
OUTPUT=""

for I in $(seq 0 $( expr $DESKTOPS - 1))
do
  if [[ $I == $FOCUSDESKTOP ]]
  then
    OUTPUT="$OUTPUT%{+u}%{F#ECEFF4}%{B#3B4252} · %{B-}%{F-}%{-u}"
    continue
  fi

  OUTPUT="$OUTPUT · "
done

echo $OUTPUT | tr "\n" "\0"
