#!/bin/sh

video=$(xclip -selection clipboard -o) ;

notify-send -a "youtube-dl" "started downloading" "started downloading $video"

youtube-dl -o "~/Downloads/youtube-dl/video" "$video"

notify-send -a "youtube-dl" "downloaded" "downloaded $video"
