#!/bin/dash	

cd $PASSWORD_STORE_DIR

passmenu -nb "#2E3440" -nf "#D8DEE9" \
	-sb "#3B4252" -sf "#ECEFF3" \
	-fn "mononoki Nerd Font-10" -p "pass:" -i \
	|| notify-send -a "Pass" -u normal "password cannot be copied" "failed to copy a password" && exit

notify-send -a "Pass" -u normal "password copied" \
	"a password has been succesfully copied to the clipboard.\n clearing in 45 seconds."
