#!/bin/bash

error () {
	notify-send -a screenshot "Error" "$1"
}

options="
1: select an area and take a screenshot to clipboard
\n2: select an area and save screenshot to file
"

sel=$(echo -en $options | dmenu -p "screenshot:" -l 15 -i)

case $(echo $sel | cut -d\: -f1)
in
	1)
		tmp=$(mktemp -p /tmp/wm screenshot.XXXXXXX.png || error "failed to create temporary file")
		import "$tmp"

		notify-send -a screenshot "Success!" \
			"The Screenshot was successfully taken, it is in the clipboard."
		rm $tmp
		;;
	*)
		error "option not implemented yet"
		;;
esac
