#!/bin/bash

error () {
	notify-send -a screenshot "Error" "$1"
}

options="
1: select an area and take a screenshot to clipboard
\n2: select an area and save screenshot to file
"

sel=$(echo -en $options | dmenu -nb "#2E3440" -nf "#D8DEE9" \
	-sb "#3B4252" -sf "#ECEFF3" \
	-fn "mononoki Nerd Font-10" -p "run:" \
	-i -l 15)

case $(echo $sel | cut -d\: -f1)
in
	1)
		tmp=$(mktemp -p /tmp/wm screenshot.XXXXXXX.png || error "failed to create temporary file")
		import "$tmp"

		notify-send -a screenshot "Success!" \
			"The Screenshot was successfully taken, it is in the clipboard."
		;;
	*)
		error "option not implemented yet"
		;;
esac
