#!/bin/bash

pacman -Qdtq | sudo pacman -Rns - &> /dev/null || echo "no orphan packages found"

cd /usr

for file in $(fd . /usr)
do
	echo -ne "\e[2K\e[G" 
	echo -n "checking $file"
	if pacman -Qo "$file" &> /dev/null; 
	then
		echo -ne "\e[2K\e[G$file is ok"
	else
		echo -e "\e[2K\e[Gno package owns $file"
		sudo rm -ri $file
	fi
done
