#!/bin/bash

DESKTOPNAME=$(xdotool get_desktop)
DESKTOPNUMS=$(xdotool get_num_desktops)

if [[ $DESKTOPNAME == $(expr $DESKTOPNUMS - 1) ]]
then
  bspc monitor -a ·
fi

bspc desktop -f next
bspc desktop prev.\!occupied -r
