#! /bin/zsh

export EDITOR=nvim
export BROWSER=firefox
export TERMINAL=kitty

killall "picom"
killall "sxhkd"
killall "lemonbar"
killall "controllemonbar"
killall "updatedesktopmodule.zsh"
mkdir -p /tmp/wm
mkfifo /tmp/wm/lemonbar
mkfifo /tmp/wm/lemonbarout

sxhkd &
xrandr -s 1360x768
picom &
hsetroot -fill ~/wallpapers/wallpaper.png
bspc desktop focused -n 0
~/.config/lemonbar/controllemonbar &
~/.scripts/lemonbar/updatedesktopmodule.zsh &
cat /tmp/wm/lemonbar | lemonbar -fMononoki -B#2E3440 -F#D8DEE9 -u2 -U#88C0D0 -gx32 -p | zsh &

xsetroot -cursor_name left_ptr

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config focused_border_color  '#88C0D0'
bspc config border_color          '#E5E9F0'
bspc config presel_feedback_color '#8FBCBB'
bspc config focus_follows_pointer  true

bspc rule -a Gimp state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#resize stuff
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
