#! /bin/zsh

export EDITOR=nvim
export BROWSER=min
export TERMINAL=kitty

killall "picom"
killall "sxhkd"
killall "lemonbar"
killall "controllemonbar"
killall "zsh"
killall "bspc"
mkdir -p /tmp/wm

sxhkd &
xrandr -s 1360x768
picom --experimental-backend &
hsetroot -fill ~/wallpapers/wallpaper.png &
bspc desktop focused -n 1

~/.config/lemonbar/controllemonbar &
zsh ~/.scripts/lemonbar/updatedesktopmodule.zsh &
zsh ~/.scripts/lemonbar/updatewindowmodule.zsh &

xsetroot -cursor_name left_ptr &

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config automatic_scheme     longest_side

bspc config focused_border_color  '#88C0D0'
bspc config border_color          '#E5E9F0'
bspc config presel_feedback_color '#8FBCBB'
bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  true

bspc rule -a Gimp state=floating
bspc rule -a \*:\*:Dialog state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#resize stuff
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
