#!/bin/bash
export EDITOR=nvim
export BROWSER=firefox
export TERMINAL=kitty

killall "picom"
killall "sxhkd"
killall "lemonbar"
killall "controllemonbar"
killall "bash"
killall "bspc"
killall "tiramisu"
mkdir -p /tmp/wm
mkfifo /tmp/wm/notifications

sxhkd &
xrandr -s 1360x768
picom --experimental-backend &
hsetroot -fill ~/wallpapers/wallpaper.png &
bspc desktop -n ·

~/.config/lemonbar/controllemonbar &
bash ~/.scripts/lemonbar/updatedesktopmodule.bash &
bash ~/.scripts/lemonbar/updatewindowmodule.bash &
bash ~/.scripts/general/notification-server.bash &

#
# xorg stuff
#
killall xcape
xsetroot -cursor_name left_ptr &
xset r rate 300 50
setxkbmap -option caps:super

killall xcap 2>/dev/null ; xcape -e "Super_L=Escape"

#
# bspwm stuff
#
bspc config border_width        0
bspc config window_gap          2
bspc config left_padding        -2
bspc config right_padding       -2
bspc config bottom_padding      -2

bspc config split_ratio          0.55
bspc config automatic_scheme     longest_side
bspc config ignore_ewmh_focus    true
bspc config external_rules_command    $HOME/.config/bspwm/external_rules

bspc config focused_border_color     '#88C0D0'
bspc config border_color             '#E5E9F0'
bspc config presel_feedback_color    '#8FBCBB'
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     true
bspc config pointer_follows_monitor   true

bspc rule -a Gimp state=floating
bspc rule -a \*:\*:Dialog state=floating
bspc rule -a \*:\*:Alert state=floating sticky=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Jami-gnome state=floating sticky=on

#resize stuff
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
