#!/bin/bash

# check if we have presel
[[ -z $(bspc query -N -n focused.automatic.tiled) ]] && exit

# check if receptacle exists
receptacle=$(bspc query -N -n .leaf.\!window -d focused)
if [[ -n $receptacle ]]
then
  echo "node=$receptacle"
  exit
fi

echo "node=biggest.local.tiled"
