#!/bin/sh

echo "opening $1"

case "$1" in
	https://www.youtube.com*)
		setsid mpv --hwdec=auto \
			"--ytdl-format=bestvideo[height<=?720][ext=mp4][fps<=30]+bestaudio[ext=m4a]" "$1"
		;;
	*)
		setsid "$BROWSER" "$1"
		;;
esac
